AllCops:
  DisabledByDefault: false
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/{rails,rake}'
    # - 'spec/**/*'

Layout/AlignArguments:
  EnforcedStyle: with_first_argument

Layout/EmptyLineAfterGuardClause:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/MultilineArrayBraceLayout:
  EnforcedStyle: new_line

Layout/MultilineAssignmentLayout:
  EnforcedStyle: same_line

Layout/MultilineHashBraceLayout:
  EnforcedStyle: new_line

# Controversial. Discuss
Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: no_space

Layout/SpaceInsideBlockBraces:
  Enabled: false
  EnforcedStyle: no_space

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Lint/BooleanSymbol:
  Enabled: false

Lint/NumberConversion:
  Enabled: true

## Metrics
Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: true
  Max: 125

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: true

Metrics/ParameterLists:
  Enabled: true

Metrics/PerceivedComplexity:
  Enabled: true

## Naming

Naming/AccessorMethodName:
  Enabled: false

# Annoying one. Needs more research
Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: true

Naming/PredicateName:
  Enabled: false

# Security

Security/Eval:
  Enabled: true

Security/YAMLLoad:
  Enabled: true

# Style

# This clashes with concerns. Investigate
Style/AccessModifierDeclarations:
  Enabled: false

# "and" is used in the controllers. Should this be allowed?
Style/AndOr:
  Enabled: true
  EnforcedStyle: conditionals

# There is some Swedish in the comments. Perhaps change and enable cop?
Style/AsciiComments:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: true

Style/Copyright:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/DoubleCopDisableDirective:
  Enabled: false

Style/DoubleNegation:
  Enabled: true

Style/FormatString:
  Enabled: true

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/GuardClause:
  Enabled: true

Style/HashSyntax:
  Enabled: true

Style/IfInsideElse:
  Enabled: true

Style/InlineComment:
  Enabled: true

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: false

Style/MethodMissingSuper:
  Enabled: false

Style/MissingElse:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/MultipleComparison:
  Enabled: true

Style/NumericPredicate:
  Enabled: false

Style/OptionHash:
  Enabled: false

Style/Semicolon:
  Enabled: true

Style/Send:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StructInheritance:
  Enabled: true

Style/Lambda:
  Enabled: true
