web:
  build: .
  env_file:
    - ./.env
  volumes:
    - .:/code
  volumes_from:
    - bundle
  ports:
    - '8090:8080'
  command: bundle exec shotgun --host 0.0.0.0 -p 8080

bundle:
  image: busybox
  volumes:
    - /bundle
